Improvements to make the script more rugged.
1) If an intermediate step fails, exit immediately. Don't try to continue.
2) Set the default installation directory to /usr/local/GNUstep, rather than /usr/GNUstep. /usr is read-only on macOS, and anyway, this conforms better to the UNIX File system Hierarchy Standard.
3) When building on Windows, check that we're not using an MSYS window. This won't work, and potentally could be disastrous as the MSYS environment is a superset of the Win32 API-compliant MINGW64 (and other) environment(s).
4) Clean up indentation etc.
5) Improve the script's output, EG by printing the current working directory when it operates, and correct some messages.

diff --git a/compile-all b/compile-all
--- a/compile-all
+++ b/compile-all
@@ -27,7 +27,8 @@ unset GNUSTEP_MAKEFILES
 if [ "$1" != "" ]; then 
    prefix="$1"
 else
-   prefix="/usr/GNUstep"
+# CJEC, 24-Feb-22: prefer /usr/local/GNUstep to /usr/GNUstep to conform better to UNIX FHS https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard . Note: Required for modern macOS, for which /usr/ is read-only
+   prefix="/usr/local/GNUstep"
 fi
 
 if [ "$2" != "" ]; then
@@ -38,12 +39,17 @@ if [ "$3" != "" ]; then
     cxxcompiler="$3"
 fi
 
-# Check if we are compiling under windows...
+# Check if we are compiling under windows. Must not use MSYS shell
 UNAME=`uname | cut -d'-' -f1`
-if [ "$UNAME" != "MINGW64_NT" ] ; then
-   if [ ! \( -d $prefix -a -w $prefix \) ] ; then
-      if [ ! \( -d $(basename $prefix) -a -w $(basename $prefix) \) ] ; then
-         NEEDSROOT="true"
+if [ "$UNAME" == "MSYS_NT" ] ; then
+   echo "$0: Cannot build in an MSYS shell. Switch to a MINGW64 shell and restart"
+   exit 1
+else
+   if [ "$UNAME" != "MINGW64_NT" ] ; then
+      if [ ! \( -d $prefix -a -w $prefix \) ] ; then
+         if [ ! \( -d $(basename $prefix) -a -w $(basename $prefix) \) ] ; then
+            NEEDSROOT="true"
+         fi
       fi
    fi
 fi
@@ -58,9 +64,9 @@ fi
 
 if gmake -v >/dev/null 2>&1
 then
-   export MAKE="gmake -j${CPUS}"
+  export MAKE="gmake -j${CPUS}"
 else
-   export MAKE="make -j${CPUS}"
+  export MAKE="make -j${CPUS}"
 fi
 
 if [ "$2" == "" ]; then
@@ -75,7 +81,7 @@ else
    export CXX=$cxxcompiler
 fi
 
-echo "$0: ==== compile-all"
+echo "$0: ==== compile-all in "`pwd`
 echo "$0: Using compiler $CC"
 echo "$0: Using c++ compiler $CXX"
 echo "$0: ===="
@@ -85,7 +91,6 @@ if [ "$UNAME" == "MINGW64_NT" ] ; then
    export cc_flags="-v -fstrict-aliasing -fno-omit-frame-pointer"
    # CJEC, 20-Jan-22: Switch MSYS to use native (real) symbolic links for building and avoiding .lnk files
    MSYS=winsymlinks:nativestrict ; export MSYS
-   env | grep MSYS
 fi
 
 # If we are building with clang, then add this to cc_flags
@@ -113,8 +118,12 @@ else
     export CXX=${cxxcompiler}
     # export LDFLAGS=-ldispatch
     export LDFLAGS=-fuse-ld=gold -ldispatch
-    echo "$0: Build command: CCFLAGS=${cc_flags} CXX=${CXX} CC=${CC} ./configure --prefix=${prefix} --with-library-combo=ng-gnu-gnu --enable-objc-arc --enable-native-objc-exceptions --with-layout=gnustep ${make_flags}"
+    echo "$0: ==== Configure Make command: CCFLAGS=${cc_flags} CXX=${CXX} CC=${CC} ./configure --prefix=${prefix} --with-library-combo=ng-gnu-gnu --enable-objc-arc --enable-native-objc-exceptions --with-layout=gnustep ${make_flags}"
     CCFLAGS=${cc_flags} CXX=${CXX} CC=${CC} ./configure --prefix=${prefix} --with-library-combo=ng-gnu-gnu --enable-objc-arc --enable-native-objc-exceptions --with-layout=gnustep ${make_flags}
+fi
+if [ ! "$?" = "0" ]; then
+        echo $0 ": ==== Configure Make FAILED"
+        exit 1
 fi
 
 if [ "$UNAME" == "MINGW64_NT" ] ; then
@@ -126,6 +135,10 @@ fi
 # Install make after configuration...
 echo "$0: ==== Installing Make..."
 $MAKE
+if [ ! "$?" = "0" ]; then
+        echo $0 ": ==== Install Make FAILED"
+        exit 1
+fi
 if [ "$UNAME" == "MINGW64_NT" ] ; then
 # CJEC, 20-Jan-22: Switch MSYS to use emulated symbolic links so that tar can create files with dangling links during make install
    MSYS=winsymlinks:lnk ; export MSYS
@@ -168,6 +181,10 @@ if [ "true" == "$NEEDSROOT" ]; then
 else
    $MAKE GNUSTEP_INSTALLATION_DOMAIN=SYSTEM install
 fi
+if [ ! "$?" = "0" ]; then
+        echo $0 ": ==== Install Base FAILED"
+        exit 1
+fi
 if [ "$UNAME" == "MINGW64_NT" ] ; then
 # CJEC, 20-Jan-22: Switch MSYS to use native (real) symbolic links for building and avoiding .lnk files
    MSYS=winsymlinks:nativestrict ; export MSYS
@@ -189,6 +206,10 @@ if [ "true" == "$NEEDSROOT" ]; then
 else
    $MAKE GNUSTEP_INSTALLATION_DOMAIN=SYSTEM install
 fi
+if [ ! "$?" = "0" ]; then
+        echo $0 ": ==== Install GUI FAILED"
+        exit 1
+fi
 if [ "$UNAME" == "MINGW64_NT" ] ; then
 # CJEC, 20-Jan-22: Switch MSYS to use native (real) symbolic links for building and avoiding .lnk files
    MSYS=winsymlinks:nativestrict ; export MSYS
@@ -208,6 +229,10 @@ if [ "true" == "$NEEDSROOT" ]; then
    ${SUDO} -u root ./install.sh $prefix $MAKE
 else
    $MAKE GNUSTEP_INSTALLATION_DOMAIN=SYSTEM install
+fi
+if [ ! "$?" = "0" ]; then
+        echo $0 ": ==== Install Backend FAILED"
+        exit 1
 fi
 if [ "$UNAME" == "MINGW64_NT" ] ; then
 # CJEC, 20-Jan-22: Switch MSYS to use native (real) symbolic links for building and avoiding .lnk files
@@ -230,6 +255,10 @@ if [ "true" == "$NEEDSROOT" ]; then
 else
    $MAKE GNUSTEP_INSTALLATION_DOMAIN=SYSTEM install
 fi
+if [ ! "$?" = "0" ]; then
+        echo $0 ": ==== Install CoreBase FAILED"
+        exit 1
+fi
 if [ "$UNAME" == "MINGW64_NT" ] ; then
 # CJEC, 20-Jan-22: Switch MSYS to use native (real) symbolic links for building and avoiding .lnk files
    MSYS=winsymlinks:nativestrict ; export MSYS
@@ -246,6 +275,10 @@ if [ "$UNAME" == "MINGW64_NT" ] ; then
    MSYS=winsymlinks:lnk ; export MSYS
 fi
 $MAKE install
+if [ ! "$?" = "0" ]; then
+        echo $0 ": ==== Install ProjectCenter FAILED"
+        exit 1
+fi
 if [ "$UNAME" == "MINGW64_NT" ] ; then
 # CJEC, 20-Jan-22: Switch MSYS to use native (real) symbolic links for building and avoiding .lnk files
    MSYS=winsymlinks:nativestrict ; export MSYS
@@ -262,6 +295,10 @@ if [ "$UNAME" == "MINGW64_NT" ] ; then
    MSYS=winsymlinks:lnk ; export MSYS
 fi
 $MAKE install
+if [ ! "$?" = "0" ]; then
+        echo $0 ": ==== Install PDFKit FAILED"
+        exit 1
+fi
 if [ "$UNAME" == "MINGW64_NT" ] ; then
 # CJEC, 20-Jan-22: Switch MSYS to use native (real) symbolic links for building and avoiding .lnk files
    MSYS=winsymlinks:nativestrict ; export MSYS
@@ -278,6 +315,10 @@ if [ "$UNAME" == "MINGW64_NT" ] ; then
    MSYS=winsymlinks:lnk ; export MSYS
 fi
 $MAKE install
+if [ ! "$?" = "0" ]; then
+        echo $0 ": ==== Install GWorkspace FAILED"
+        exit 1
+fi
 if [ "$UNAME" == "MINGW64_NT" ] ; then
 # CJEC, 20-Jan-22: Switch MSYS to use native (real) symbolic links for building and avoiding .lnk files
    MSYS=winsymlinks:nativestrict ; export MSYS
@@ -293,6 +334,10 @@ if [ "$UNAME" == "MINGW64_NT" ] ; then
    MSYS=winsymlinks:lnk ; export MSYS
 fi
 $MAKE install
+if [ ! "$?" = "0" ]; then
+        echo $0 ": ==== Install SystemPreferences FAILED"
+        exit 1
+fi
 if [ "$UNAME" == "MINGW64_NT" ] ; then
 # CJEC, 20-Jan-22: Switch MSYS to use native (real) symbolic links for building and avoiding .lnk files
    MSYS=winsymlinks:nativestrict ; export MSYS
@@ -328,4 +373,4 @@ else
    fi
 fi
 
-echo "$0: ==== compile-all Done."
+echo "$0: ==== compile-all Done. Use 'openapp GWorkspace' to test the installation"
